services:
  streamlit:
    build:
      context: ./frontend_src
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    volumes:
      - shared-volume:/data
      - nltk_data:/root/nltk_data
      - ./frontend_src:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: bash -c "streamlit run /app/app.py --server.address 0.0.0.0"
    restart: always

  data_processing:
    build:
      context: ./data_sources_processing_src
    container_name: data_processor
    volumes:
      - shared-volume:/data
      - ./data_sources_processing_src/data_sources_processing/datasets_metadata.json:/data/datasets_metadata.json
      - ./data_sources_processing_src/crontab:/etc/cron.d/processing_cron
      - cron_logs:/var/log
      - ./data_sources_processing_src:/app
    command: bash /app/run_cron.sh
    restart: always

volumes:
  shared-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data
  nltk_data:
  cron_logs:
