import streamlit as st


@st.dialog("Disclaimer and Terms of Use", width="large")
def show_disclaimer(local_storage):
    """Show disclaimer message at the startup"""
    text = """
    The information provided on this platform is for informational purposes only. The Global
    Child Protection Area of Responsibility (GCP AoR) makes no representations or warranties,
    expressed or implied, regarding the accuracy, completeness, or suitability for any particular
    purpose of the information available. The GCP AoR is not liable for any loss, damage, or
    liability arising from the use of this platform, and all use is at the user’s own risk.<br>

    <b>Content and Updates</b><br>
    The GCP AoR may update or modify content on this platform without notice. Users are
    advised not to rely solely on the information provided here for critical decisions.<br>

    <b>Third-Party Links and Information</b><br>
    This platform may include links to third-party websites and may contain advice, opinions,
    and statements from external providers. Reliance upon any such advice, opinion, statement,
    or other information shall also be at the User’s own risk. The GCP AoR does not control and is
    not responsible for the content or accuracy of these external sites. Links to third-party sites
    do not imply endorsement by the GCP AoR.<br>

    <b>Geographical and Political Information</b><br>
    The presentation of geographical or political information does not imply endorsement by the
    GCP AoR. Terms like &quot;country&quot; refer generally to regions as appropriate, without assumptions
    regarding legal status or boundaries.<br>

    <b>NLP and AI-Generated Content</b><br>
    Content generated by Natural Language Processing (NLP) and AI (Artificial Intelligence)
    technologies is incorporated to enhance accessibility and understanding. However, this AI-
    generated content may contain inaccuracies or omissions and is not guaranteed for accuracy.
    Users should exercise caution and consult additional sources when making important
    decisions based on this content. The GCP AoR disclaims all liability for any errors in AI-
    generated content and reserves the right to modify or remove such content at any time. <br>

    By using this platform, I acknowledge and agree to these terms.

    """
    st.html(text)

    if st.button("Accept", use_container_width=True):
        local_storage.setItem("cpaor_consent_confirm", "true")
        st.rerun()
