name: Feature Request
description: Template for creating new feature requests.
title: "Feature: [Feature-Title]"
labels: ["feature-request"]
body:
  - type: textarea
    id: feature_request
    attributes:
      label: Feature Request
      value: |
          **As a** [User Type], **I want** [Feature/Goal] **so that** [Reason/Value].
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
