name: User Story
description: Template for creating new feature requests.
title: "US-[ID]: [US-Title]"
labels: ["feature-request"]
body:
  - type: textarea
    id: feature_request
    attributes:
      label: Feature Request
      value: |
          **As a** [User Type], **I want** [Feature/Goal] **so that** [Reason/Value].
  - type: markdown
    attributes:
      value: |
        ---
  - type: checkboxes
    id: definition_of_done
    attributes:
      label:  Definition of Done
      description: Criteria that must be met for the user story to be complete
      options:
        - label: If applicable, Relevant tests (unit, integration, etc.) have been created and passed.
        - label: No critical bugs or security vulnerabilities remain.
        - label: Documentation is updated (including behavior documents, technical documentation, etc.).
        - label: All related PRs are merged to develop branch.
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
