{{- $secrets := dict }}
{{- range $k, $v := .Values.streamlit.secrets }}
{{- if $v }}{{- $_ := set $secrets $k $v }}{{- end }}
{{- end }}
{{- if $secrets }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "cpaor-data-viz-dashboard-helm.fullname" . }}-streamlit-secrets
  labels:
    app: {{ template "cpaor-data-viz-dashboard-helm.fullname" . }}
    component: streamlit
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  {{- range $k, $v := $secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
