kind: Secret
apiVersion: v1
metadata:
  name: {{ template "cpaor-data-viz-dashboard-helm.fullname" . }}-app-secrets
  labels:
    component: streamlit
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  APP_ENVIRONMENT: {{ required "APP_ENVIRONMENT" .Values.streamlit.secrets.APP_ENVIRONMENT | quote }}
  GA_TRACKING_ID: {{ required "GA_TRACKING_ID" .Values.streamlit.secrets.GA_TRACKING_ID | quote }}
