apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cpaor-data-viz-dashboard-helm.fullname" . }}-shared-volume
  labels:
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.sharedVolume.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.sharedVolume.persistence.size }}
