kind: Secret
apiVersion: v1
metadata:
  name: {{ template "cpaor-data-viz-dashboard-helm.fullname" . }}-secrets
  labels:
    component: data-processing
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ required "OPENAI_API_KEY" .Values.dataProcessing.secrets.OPENAI_API_KEY | quote }}
  ACLED_API_KEY: {{ required "ACLED_API_KEY" .Values.dataProcessing.secrets.ACLED_API_KEY | quote }}
  CPAOR_EMAIL: {{ required "CPAOR_EMAIL" .Values.dataProcessing.secrets.CPAOR_EMAIL | quote }}
  ACAPS_PASSWORD: {{ required "ACAPS_PASSWORD" .Values.dataProcessing.secrets.ACAPS_PASSWORD | quote }}
